//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendence_Leave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLogin
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailID { get; set; }
        public string Phoneno { get; set; }
        public string Fullname { get; set; }
        public string Designation { get; set; }
        public string Manager { get; set; }
        public string Grade { get; set; }
        public string employeeStatus { get; set; }
        public string city { get; set; }
    }
}
